# Generated by Django 2.2.3 on 2019-07-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playpif', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sequencia',
        ),
    ]
